CREATE TABLE `Template_PollData` (
  `submissionNumber` int(11) NOT NULL AUTO_INCREMENT,
  `id` varchar(45) DEFAULT NULL,
  `response1` int(1) NOT NULL,
  `response2` int(1) DEFAULT NULL,
  `response3` int(1) DEFAULT NULL,
  `response4` int(1) DEFAULT NULL,
  `response5` int(1) DEFAULT NULL,
  `response6` int(1) DEFAULT NULL,
  `response7` int(1) DEFAULT NULL,
  `response8` int(1) DEFAULT NULL,
  `response9` int(1) DEFAULT NULL,
  `response10` int(1) DEFAULT NULL,
  `response11` int(1) DEFAULT NULL,
  `response12` int(1) DEFAULT NULL,
  `response13` int(1) DEFAULT NULL,
  `response14` int(1) DEFAULT NULL,
  `response15` int(1) DEFAULT NULL,
  `response16` int(1) DEFAULT NULL,
  PRIMARY KEY (`submissionNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
